/**
 * Seed Data para Skills do Agente IA
 *
 * 30 Skills organizadas em 3 níveis:
 * - Básico (10): Para iniciantes em cada área
 * - Intermediário (10): Para quem já tem experiência
 * - Avançado (10): Para especialistas e empresas
 *
 * Foco em: Vendas diretas, Marketing Digital, Gestão de Mídias Sociais,
 *          Marketplace, Dropshipping, Processos Operacionais Comerciais
 */

import { getDb } from "./db";
import { skills } from "../../database/schemas/schema-skills";
import { eq } from "drizzle-orm";

const SEED_SKILLS = [
  // ==========================================================================
  // SKILLS BÁSICAS (10)
  // ==========================================================================
  {
    name: "Copywriting Básico",
    slug: "copy-basico",
    description: "Aprenda a criar textos persuasivos para redes sociais, e-mails e landing pages. Domine a arte de escrever que vende através de palavras.",
    shortDescription: "Crie textos de vendas simples e eficazes para redes sociais.",
    level: "basic" as const,
    category: "copywriting",
    subcategory: "textos",
    price: 1900,
    originalPrice: null,
    iconEmoji: "✍️",
    badge: null,
    features: JSON.stringify([
      "Templates de captions para Instagram",
      "Estrutura básica de texto persuasivo",
      "Geração de headlines efetivos",
      "Hashtags básicas por nicho",
      "Chamadas para ação (CTAs)",
    ]),
    requirements: JSON.stringify(["Conhecimento básico de marketing"]),
    integrations: JSON.stringify(["Instagram", "Facebook", "WhatsApp"]),
    useCases: JSON.stringify(["Posts em redes sociais", "Legendas de Instagram", "WhatsApp"]),
    targetAudience: "beginners" as const,
    status: "active" as const,
    sortOrder: 1,
  },
  {
    name: "Gestão de Redes Sociais",
    slug: "gestao-redes-basico",
    description: "Aprenda a gerenciar suas redes sociais de forma organizada com calendários e agendamentos. Ideal para quem está começando.",
    shortDescription: "Gerencie suas redes sociais com organização e calendário simples.",
    level: "basic" as const,
    category: "social_media",
    subcategory: "gestao",
    price: 2400,
    originalPrice: null,
    iconEmoji: "📱",
    badge: "Popular",
    features: JSON.stringify([
      "Calendário editorial básico",
      "Agendamento de posts",
      "Respostas automáticas simples",
      "Relatórios mensais",
      "Gestão de comentarios",
    ]),
    requirements: JSON.stringify(["Contas nas redes sociais"]),
    integrations: JSON.stringify(["Instagram", "Facebook"]),
    useCases: JSON.stringify(["Postagem diária", "Agendamento", "Relatórios"]),
    targetAudience: "beginners" as const,
    status: "active" as const,
    sortOrder: 2,
  },
  {
    name: "Atendimento ao Cliente",
    slug: "atendimento-basico",
    description: "oferece um atendimento ao cliente rápido e eficiente usando respostas pré-configuradas e automação básica.",
    shortDescription: "Responda dúvidas de clientes de forma rápida e eficiente.",
    level: "basic" as const,
    category: "customer_service",
    subcategory: "atendimento",
    price: 1800,
    originalPrice: null,
    iconEmoji: "💬",
    badge: null,
    features: JSON.stringify([
      "Respostas pré-configuradas",
      "Classificação de mensagens",
      "Escalação automática",
      "Histórico de conversas",
      "Respostas rápidas",
    ]),
    requirements: JSON.stringify(["Plataforma de mensagens configurada"]),
    integrations: JSON.stringify(["WhatsApp", "Instagram", "Messenger"]),
    useCases: JSON.stringify(["Suporte via chat", "FAQ automatizado", "Escalação"]),
    targetAudience: "all" as const,
    status: "active" as const,
    sortOrder: 3,
  },
  {
    name: "Analytics Básico",
    slug: "analytics-basico",
    description: "Entenda as métricas mais importantes das suas campanhas e acompanhe o crescimento de forma simples.",
    shortDescription: "Entenda métricas simples e acompanhe seu desempenho.",
    level: "basic" as const,
    category: "analytics",
    subcategory: "metricas",
    price: 1500,
    originalPrice: null,
    iconEmoji: "📊",
    badge: null,
    features: JSON.stringify([
      "Dashboard de métricas principais",
      "Gráficos de crescimento",
      "Análise de engajamento",
      "Exportação de dados",
      "Relatórios automáticos",
    ]),
    requirements: JSON.stringify(["Conta comercial ou pixels"]),
    integrations: JSON.stringify(["Instagram Insights", "Facebook Analytics"]),
    useCases: JSON.stringify(["Análise de posts", "Relatórios de growth", "Métricas de engajamento"]),
    targetAudience: "beginners" as const,
    status: "active" as const,
    sortOrder: 4,
  },
  {
    name: "Criação de Conteúdo",
    slug: "criacao-conteudo-basico",
    description: "Gere ideias criativas e textos para seus posts diários de forma consistente e alinhada com sua marca.",
    shortDescription: "Gere ideias e textos para seus posts diários.",
    level: "basic" as const,
    category: "content",
    subcategory: "criacao",
    price: 2200,
    originalPrice: null,
    iconEmoji: "🎨",
    badge: null,
    features: JSON.stringify([
      "Geração de ideias de posts",
      "Textos para Stories",
      "Legendas otimizadas",
      "Calendário de conteúdo",
      "Tendências do momento",
    ]),
    requirements: JSON.stringify(["Conhecimento do nicho"]),
    integrations: JSON.stringify(["Instagram", "TikTok", "Facebook"]),
    useCases: JSON.stringify(["Ideação de conteúdo", "Calendário editorial", "Stories"]),
    targetAudience: "beginners" as const,
    status: "active" as const,
    sortOrder: 5,
  },
  {
    name: "E-mail Marketing",
    slug: "email-marketing-basico",
    description: "Crie e envie newsletters e campanhas de e-mail que engajam e convertem sua lista de contatos.",
    shortDescription: "Crie e envie newsletters e campanhas de e-mail.",
    level: "basic" as const,
    category: "email",
    subcategory: "campanhas",
    price: 2000,
    originalPrice: null,
    iconEmoji: "📧",
    badge: null,
    features: JSON.stringify([
      "Templates de e-mail responsivos",
      "Segmentação básica de lista",
      "Automação de envios",
      "Análise de taxa de abertura",
      "Sequências de nutrição",
    ]),
    requirements: JSON.stringify(["Lista de e-mails"]),
    integrations: JSON.stringify(["Mailchimp", "RD Station", "Integrations nativas"]),
    useCases: JSON.stringify(["Newsletters", "Campanhas promocionais", "Nutrição de leads"]),
    targetAudience: "all" as const,
    status: "active" as const,
    sortOrder: 6,
  },
  {
    name: "Landing Pages",
    slug: "landing-page-basico",
    description: "Crie páginas de captura de leads otimizadas para converter visitantes em contatos qualificados.",
    shortDescription: "Crie páginas de captura simples e eficazes.",
    level: "basic" as const,
    category: "landing_pages",
    subcategory: "paginas",
    price: 2600,
    originalPrice: null,
    iconEmoji: "🌐",
    badge: null,
    features: JSON.stringify([
      "Templates de landing page",
      "Formulários de captura",
      "Integração com e-mail marketing",
      "Design mobile-first",
      "Otimização de conversão",
    ]),
    requirements: JSON.stringify(["Conhecimento de copy"]),
    integrations: JSON.stringify(["WordPress", "Leadpages", "Carrd"]),
    useCases: JSON.stringify(["Captura de leads", "Eventos", "Webinars"]),
    targetAudience: "beginners" as const,
    status: "active" as const,
    sortOrder: 7,
  },
  {
    name: "Gestão de Leads",
    slug: "gestao-leads-basico",
    description: "Organize e acompanhe seus leads e prospectos de forma eficiente para não perder nenhuma oportunidade.",
    shortDescription: "Organize e acompanhe seus leads e prospectos.",
    level: "basic" as const,
    category: "crm",
    subcategory: "leads",
    price: 1700,
    originalPrice: null,
    iconEmoji: "👥",
    badge: null,
    features: JSON.stringify([
      "Cadastro de leads",
      "Etiquetagem e segmentação",
      "Pipeline visual",
      "Lembretes de follow-up",
      "Histórico de interações",
    ]),
    requirements: JSON.stringify(["Processo de captura definido"]),
    integrations: JSON.stringify(["Google Sheets", "Notion", "CRM básico"]),
    useCases: JSON.stringify(["Organização de prospecção", "Acompanhamento de vendas", "Lead scoring"]),
    targetAudience: "all" as const,
    status: "active" as const,
    sortOrder: 8,
  },
  {
    name: "Link Tracking",
    slug: "traking-links-basico",
    description: "Rastreie cliques e conversões dos seus links para saber exatamente o que está funcionando.",
    shortDescription: "Rastreie cliques e conversões dos seus links.",
    level: "basic" as const,
    category: "tracking",
    subcategory: "links",
    price: 1400,
    originalPrice: null,
    iconEmoji: "🔗",
    badge: null,
    features: JSON.stringify([
      "Links encurtados personalizados",
      "UTM parameters automático",
      "Relatório de cliques",
      "QR Codes",
      "Redirects condicionais",
    ]),
    requirements: JSON.stringify(["Presença online"]),
    integrations: JSON.stringify(["Bitly", "Rebrandly", "UTM.io"]),
    useCases: JSON.stringify(["Rastreamento de campañas", "Redes sociais", "E-mail marketing"]),
    targetAudience: "beginners" as const,
    status: "active" as const,
    sortOrder: 9,
  },
  {
    name: "Funil de Vendas",
    slug: "funil-basico",
    description: "Monte funis simples para converter visitantes em leads qualificados e iniciar seu processo de vendas.",
    shortDescription: "Monte funis simples para converter visitantes em leads.",
    level: "basic" as const,
    category: "sales",
    subcategory: "funil",
    price: 2800,
    originalPrice: null,
    iconEmoji: "🎯",
    badge: null,
    features: JSON.stringify([
      "Templates de funil",
      "Página de obrigado",
      "Sequência de e-mails",
      "Upsell básico",
      "Análise de conversão",
    ]),
    requirements: JSON.stringify(["Produto/serviço para vender"]),
    integrations: JSON.stringify(["E-mail marketing", "Landing pages", "Checkout"]),
    useCases: JSON.stringify(["Captura de leads", "Venda de produtos", "入会"]),
    targetAudience: "beginners" as const,
    status: "active" as const,
    sortOrder: 10,
  },

  // ==========================================================================
  // SKILLS INTERMEDIÁRIAS (10)
  // ==========================================================================
  {
    name: "Facebook Ads Intermediário",
    slug: "facebook-ads-inter",
    description: "Crie campanhas segmentadas e otimizadas no Facebook Ads Manager para alcançar seu público-alvo e maximizar resultados.",
    shortDescription: "Crie campanhas segmentadas e otimizadas no Facebook Ads.",
    level: "intermediate" as const,
    category: "ads",
    subcategory: "facebook",
    price: 4900,
    originalPrice: 5900,
    iconEmoji: "📢",
    badge: "Popular",
    features: JSON.stringify([
      "Campanhas completas do Facebook",
      "Pixel de conversão",
      "Lookalike audiences",
      "Remarketing avançado",
      "Otimização de orçamento",
    ]),
    requirements: JSON.stringify(["Conta Business Manager", "Produtos para vender"]),
    integrations: JSON.stringify(["Facebook Ads Manager", "Instagram", "Pixel"]),
    useCases: JSON.stringify(["Vendas", "Geração de leads", "Tráfego"]),
    targetAudience: "intermediates" as const,
    status: "active" as const,
    sortOrder: 11,
  },
  {
    name: "Crescimento no Instagram",
    slug: "instagram-growth-inter",
    description: "Estratégias avançadas para crescer seguidores orgânicos e engajados no Instagram de forma consistente.",
    shortDescription: "Estratégias avançadas para crescer seguidores orgânicos.",
    level: "intermediate" as const,
    category: "social_media",
    subcategory: "instagram",
    price: 4400,
    originalPrice: null,
    iconEmoji: "📸",
    badge: null,
    features: JSON.stringify([
      "Estratégia de conteúdo completa",
      "Hashtag inteligente",
      "Engajamento automatizado",
      "Análise de crescimento",
      "Collaborative posts",
    ]),
    requirements: JSON.stringify(["Conta profissional", "Nicho definido"]),
    integrations: JSON.stringify(["Instagram", "Later", "Planoly"]),
    useCases: JSON.stringify(["Growth orgânico", "Engajamento", "Brand building"]),
    targetAudience: "intermediates" as const,
    status: "active" as const,
    sortOrder: 12,
  },
  {
    name: "WhatsApp Business Pro",
    slug: "whatsapp-business-inter",
    description: "Automatize vendas e atendimento via WhatsApp com catálogos, broadcast e integração com CRM.",
    shortDescription: "Automatize vendas e atendimento via WhatsApp.",
    level: "intermediate" as const,
    category: "automation",
    subcategory: "whatsapp",
    price: 5400,
    originalPrice: null,
    iconEmoji: "💬",
    badge: "Novo",
    features: JSON.stringify([
      "Respostas automáticas avançadas",
      "Catálogo de produtos",
      "Broadcast segmentado",
      "Integração CRM",
      "Macros personalizados",
    ]),
    requirements: JSON.stringify(["WhatsApp Business", "Estratégia de vendas"]),
    integrations: JSON.stringify(["WhatsApp Business API", "Zapier", "CRM"]),
    useCases: JSON.stringify(["Vendas", "Atendimento", "Broadcast"]),
    targetAudience: "intermediates" as const,
    status: "active" as const,
    sortOrder: 13,
  },
  {
    name: "SEO para Buscadores",
    slug: "seo-inter",
    description: "Otimize seu conteúdo para aparecer nas primeiras posições dos buscadores como Google e Bing.",
    shortDescription: "Otimize seu conteúdo para aparecer nas buscas.",
    level: "intermediate" as const,
    category: "seo",
    subcategory: "otimizacao",
    price: 3900,
    originalPrice: null,
    iconEmoji: "🔍",
    badge: null,
    features: JSON.stringify([
      "Pesquisa de palavras-chave",
      "On-page SEO completo",
      "Link building",
      "Análise de ranking",
      "Technical SEO básico",
    ]),
    requirements: JSON.stringify(["Site ou blog", "Conhecimento de nicho"]),
    integrations: JSON.stringify(["Google Search Console", "SEMrush", "Ahrefs"]),
    useCases: JSON.stringify(["Tráfego orgânico", "Blog", "SEO local"]),
    targetAudience: "intermediates" as const,
    status: "active" as const,
    sortOrder: 14,
  },
  {
    name: "Dropshipping Operações",
    slug: "dropshipping-inter",
    description: "Gerencie operações completas de dropshipping com integração a marketplaces e gestão de pedidos.",
    shortDescription: "Gerencie operações completas de dropshipping.",
    level: "intermediate" as const,
    category: "ecommerce",
    subcategory: "dropshipping",
    price: 6400,
    originalPrice: 7900,
    iconEmoji: "📦",
    badge: null,
    features: JSON.stringify([
      "Integração Mercado Livre",
      "Gestão de pedidos",
      "Rastreamento automático",
      "Sincronização de estoque",
      "Automação de envios",
    ]),
    requirements: JSON.stringify(["Contas nos marketplaces", "Fornecedor de dropshipping"]),
    integrations: JSON.stringify(["Mercado Livre", "Shopee", "AliExpress"]),
    useCases: JSON.stringify(["Loja dropshipping", "Multi-marketplaces", "Scale-up"]),
    targetAudience: "intermediates" as const,
    status: "active" as const,
    sortOrder: 15,
  },
  {
    name: "Copywriting para E-mail",
    slug: "copy-email-inter",
    description: "Escreva e-mails que vendem e convertem, desde sequências de nutrição até lançamentos de produtos.",
    shortDescription: "Escreva e-mails que vendem e convertem.",
    level: "intermediate" as const,
    category: "copywriting",
    subcategory: "email",
    price: 3600,
    originalPrice: null,
    iconEmoji: "✉️",
    badge: null,
    features: JSON.stringify([
      "Sequências de e-mail completas",
      "E-mails de lançamento",
      "Testes A/B",
      "Automação de nutrição",
      "Copy para transactional",
    ]),
    requirements: JSON.stringify(["Lista de e-mails", "Conhecimento de copy"]),
    integrations: JSON.stringify(["Mailchimp", "ActiveCampaign", "ConvertKit"]),
    useCases: JSON.stringify(["Sequências de venda", "Lançamentos", "Nutrição"]),
    targetAudience: "intermediates" as const,
    status: "active" as const,
    sortOrder: 16,
  },
  {
    name: "Video Marketing",
    slug: "video-marketing-inter",
    description: "Crie e distribua vídeos para marketing de forma estratégica e escalável.",
    shortDescription: "Crie e distribua vídeos para marketing.",
    level: "intermediate" as const,
    category: "content",
    subcategory: "video",
    price: 4200,
    originalPrice: null,
    iconEmoji: "🎬",
    badge: null,
    features: JSON.stringify([
      "Scripts de vídeo",
      "Edição básica de vídeo",
      "Thumbnail otimizado",
      "Distribuição multi-plataforma",
      "Shorts para reels",
    ]),
    requirements: JSON.stringify(["Câmera ou celular", "Software de edição"]),
    integrations: JSON.stringify(["CapCut", "Canva", "YouTube"]),
    useCases: JSON.stringify(["Reels/TikTok", "YouTube", "Anúncios em vídeo"]),
    targetAudience: "intermediates" as const,
    status: "active" as const,
    sortOrder: 17,
  },
  {
    name: "Marketing de Afiliados",
    slug: "afiliados-inter",
    description: "Maximize suas comissões de afiliado com estratégias avançadas de promoção e rastreamento.",
    shortDescription: "Estratégias para maximizar comissões de afiliados.",
    level: "intermediate" as const,
    category: "affiliate",
    subcategory: "marketing",
    price: 4800,
    originalPrice: null,
    iconEmoji: "🤝",
    badge: null,
    features: JSON.stringify([
      "Criação de banners",
      "Links de rastreamento",
      "Materiais promocionais",
      "Relatórios de comissões",
      "Campanhas de afiliado",
    ]),
    requirements: JSON.stringify(["Plataformas de afiliados", "Estratégia de conteúdo"]),
    integrations: JSON.stringify(["Hotmart", "Monetizze", "Kiwi"]),
    useCases: JSON.stringify(["Promoção de infoprodutos", "Comparisons", "Reviews"]),
    targetAudience: "intermediates" as const,
    status: "active" as const,
    sortOrder: 18,
  },
  {
    name: "CRM Avançado",
    slug: "crm-avancado-inter",
    description: "Gerencie clientes com CRM completo incluindo automação de tarefas, score de leads e integrações.",
    shortDescription: "Gerencie clientes com CRM completo e automatizado.",
    level: "intermediate" as const,
    category: "crm",
    subcategory: "gestao",
    price: 5600,
    originalPrice: 6900,
    iconEmoji: "💼",
    badge: null,
    features: JSON.stringify([
      "Pipeline personalizado",
      "Automação de tarefas",
      "Score de leads",
      "Integração telefonia",
      "Previsão de vendas",
    ]),
    requirements: JSON.stringify(["Processo de vendas definido", "CRM chosen"]),
    integrations: JSON.stringify(["Salesforce", "HubSpot", "Pipedrive"]),
    useCases: JSON.stringify(["Gestão de vendas", "Automação comercial", "Previsões"]),
    targetAudience: "intermediates" as const,
    status: "active" as const,
    sortOrder: 19,
  },
  {
    name: "Lançamentos Digitais",
    slug: "lancamento-inter",
    description: "Planeje e execute lançamentos de produtos digitais com funis de lançamento e automação completa.",
    shortDescription: "Planeje e execute lançamentos de produtos digitais.",
    level: "intermediate" as const,
    category: "sales",
    subcategory: "lancamentos",
    price: 6200,
    originalPrice: null,
    iconEmoji: "🚀",
    badge: null,
    features: JSON.stringify([
      "Funil de lançamento completo",
      "Página de vendas",
      "Countdown e escassez",
      "Follow-up automático",
      "Análise de conversão",
    ]),
    requirements: JSON.stringify(["Produto digital", "Lista de e-mails"]),
    integrations: JSON.stringify(["Kajabi", "Eduzz", "Hotmart"]),
    useCases: JSON.stringify(["Lançamento de curso", "Software", "Consultoria"]),
    targetAudience: "intermediates" as const,
    status: "active" as const,
    sortOrder: 20,
  },

  // ==========================================================================
  // SKILLS AVANÇADAS (10)
  // ==========================================================================
  {
    name: "Facebook Ads Master",
    slug: "facebook-ads-avancado",
    description: "Domine campanhas complexas com ROAS máximo usando estratégias avançadas de segmentação e otimização.",
    shortDescription: "Domine campanhas complexas com ROAS máximo.",
    level: "advanced" as const,
    category: "ads",
    subcategory: "facebook",
    price: 8900,
    originalPrice: 11900,
    iconEmoji: "🎯",
    badge: "Premium",
    features: JSON.stringify([
      "Campanhas escaláveis",
      "Audiências avançadas",
      "Otimização de budget",
      "Atribuição de conversão",
      "Testes de criatividade",
    ]),
    requirements: JSON.stringify(["Budget mínimo de R$ 5k/mês", "Produtos validados"]),
    integrations: JSON.stringify(["Facebook Ads Manager", "Google Analytics", "CRM"]),
    useCases: JSON.stringify(["Scale de campañas", "Lançamentos", "E-commerce"]),
    targetAudience: "advanced" as const,
    status: "active" as const,
    sortOrder: 21,
  },
  {
    name: "Google Ads Expert",
    slug: "google-ads-avancado",
    description: "Estratégias avançadas para Google Ads incluindo Search, Display, Shopping e YouTube Ads.",
    shortDescription: "Estratégias avançadas para Google Ads e Remarketing.",
    level: "advanced" as const,
    category: "ads",
    subcategory: "google",
    price: 9400,
    originalPrice: 12900,
    iconEmoji: "🔵",
    badge: null,
    features: JSON.stringify([
      "Search Ads avançados",
      "Display Network",
      "Shopping Campaigns",
      "YouTube Ads",
      "Remarketing dinámico",
    ]),
    requirements: JSON.stringify(["Budget mínimo de R$ 3k/mês", "Website com conversão"]),
    integrations: JSON.stringify(["Google Ads", "Tag Manager", "Analytics"]),
    useCases: JSON.stringify(["Tráfego pago", "E-commerce", "Leads B2B"]),
    targetAudience: "advanced" as const,
    status: "active" as const,
    sortOrder: 22,
  },
  {
    name: "E-commerce Completo",
    slug: "ecommerce-full-avancado",
    description: "Gerencie loja virtual completa com gateway de pagamento, gestão de estoque e automação fiscal.",
    shortDescription: "Gerencie loja virtual completa com todas as integrações.",
    level: "advanced" as const,
    category: "ecommerce",
    subcategory: "loja",
    price: 12400,
    originalPrice: 15900,
    iconEmoji: "🛒",
    badge: "Vendas",
    features: JSON.stringify([
      "Loja completa com checkout",
      "Múltiplos gateways de pagamento",
      "Gestão de estoque",
      "Nota fiscal automática",
      "Automação de envios",
    ]),
    requirements: JSON.stringify(["CNPJ", "Produtos para vender", "Integração logística"]),
    integrations: JSON.stringify(["Stripe", "MercadoPago", "Nuvemshop"]),
    useCases: JSON.stringify(["Loja virtual", "Scale-up", "Multi-produtos"]),
    targetAudience: "advanced" as const,
    status: "active" as const,
    sortOrder: 23,
  },
  {
    name: "Marketplace Master",
    slug: "marketplace-full-avancado",
    description: "Gerencie múltiplos marketplaces simultaneamente com sincronização unificada de produtos e pedidos.",
    shortDescription: "Gerencie múltiplos marketplaces simultaneamente.",
    level: "advanced" as const,
    category: "marketplace",
    subcategory: "multi",
    price: 11400,
    originalPrice: 14900,
    iconEmoji: "🏪",
    badge: null,
    features: JSON.stringify([
      "Mercado Livre unificado",
      "Shopee integrado",
      "Hotmart para infoprodutos",
      "Sincronização unificada",
      "Gestão centralizada",
    ]),
    requirements: JSON.stringify(["Contas verificadas", "Produtos para todos marketplaces"]),
    integrations: JSON.stringify(["Mercado Livre", "Shopee", "Hotmart", "Tiny ERP"]),
    useCases: JSON.stringify(["Multi-marketplaces", "Scale de vendas", "Gestão unificada"]),
    targetAudience: "advanced" as const,
    status: "active" as const,
    sortOrder: 24,
  },
  {
    name: "Funil de Vendas Enterprise",
    slug: "funil-vendas-full-avancado",
    description: "Funis complexos B2B com múltiplas etapas, integrações e automação para vendas de alto ticket.",
    shortDescription: "Funis complexos B2B com múltiplas etapas e integrações.",
    level: "advanced" as const,
    category: "sales",
    subcategory: "enterprise",
    price: 14900,
    originalPrice: 19900,
    iconEmoji: "🏢",
    badge: "Premium",
    features: JSON.stringify([
      "Funis multi-etapa",
      "CRM enterprise",
      "Webinars automatizados",
      "Alta conversão",
      "Gestão de objections",
    ]),
    requirements: JSON.stringify(["Processo comercial definido", "Equipo de vendas"]),
    integrations: JSON.stringify(["Salesforce", "Zoom", "Calendly"]),
    useCases: JSON.stringify(["Vendas B2B", "Alto ticket", "Consultoria"]),
    targetAudience: "enterprise" as const,
    status: "active" as const,
    sortOrder: 25,
  },
  {
    name: "Mídia Paga Master",
    slug: "marketing-midia-avancado",
    description: "Estratégias multi-canal de mídia paga avançada cobrindo Google, Facebook, Instagram, TikTok e LinkedIn.",
    shortDescription: "Estratégias multi-canal de mídia paga avançada.",
    level: "advanced" as const,
    category: "ads",
    subcategory: "multi",
    price: 10900,
    originalPrice: 13900,
    iconEmoji: "📺",
    badge: null,
    features: JSON.stringify([
      "Facebook + Instagram Ads",
      "Google Ads completo",
      "TikTok Ads",
      "LinkedIn Ads",
      "Attribution modeling",
    ]),
    requirements: JSON.stringify(["Budget mínimo de R$ 10k/mês", "Múltiplos produtos"]),
    integrations: JSON.stringify(["Todas plataformas de ads", "Analytics unificado"]),
    useCases: JSON.stringify(["Mídia paga completa", "Scale", "Multi-canais"]),
    targetAudience: "enterprise" as const,
    status: "active" as const,
    sortOrder: 26,
  },
  {
    name: "Automação Completa",
    slug: "automacao-full-avancado",
    description: "Automação total de processos comerciais e marketing usando IA e integrações avançadas.",
    shortDescription: "Automação total de processos comerciais e marketing.",
    level: "advanced" as const,
    category: "automation",
    subcategory: "full",
    price: 13400,
    originalPrice: 16900,
    iconEmoji: "⚙️",
    badge: "Popular",
    features: JSON.stringify([
      "Zapier/Make integrations",
      "Sequências avançadas",
      "Inteligência artificial",
      "Analytics preditivo",
      "Automação de decisões",
    ]),
    requirements: JSON.stringify(["Mapear processos", "Múltiplas ferramentas"]),
    integrations: JSON.stringify(["Zapier", "Make", "OpenAI", "Slack"]),
    useCases: JSON.stringify(["Automação comercial", "Marketing automation", "Customer success"]),
    targetAudience: "advanced" as const,
    status: "active" as const,
    sortOrder: 27,
  },
  {
    name: "Analytics Intelligence",
    slug: "analytics-full-avancado",
    description: "Análise avançada com dashboards customizados, funis de conversão e previsões com machine learning.",
    shortDescription: "Análise avançada com dashboards e previsões.",
    level: "advanced" as const,
    category: "analytics",
    subcategory: "intelligence",
    price: 9800,
    originalPrice: 12900,
    iconEmoji: "📈",
    badge: null,
    features: JSON.stringify([
      "Dashboards customizados",
      "Análise de funil",
      "Previsão de receita",
      "Machine learning",
      "Análise de cohort",
    ]),
    requirements: JSON.stringify(["Dados históricos", "Data warehouse básico"]),
    integrations: JSON.stringify(["BigQuery", "Looker", "Tableau"]),
    useCases: JSON.stringify(["Business intelligence", "Previsões", "Decisões data-driven"]),
    targetAudience: "enterprise" as const,
    status: "active" as const,
    sortOrder: 28,
  },
  {
    name: "Vendas Corporativas B2B",
    slug: "vendas-corporativas-avancado",
    description: "Estratégias avançadas para vendas B2B de alto ticket com prospecção ativa e negociação sofisticada.",
    shortDescription: "Estratégias avançadas para vendas B2B de alto ticket.",
    level: "advanced" as const,
    category: "b2b",
    subcategory: "corporativo",
    price: 15900,
    originalPrice: 19900,
    iconEmoji: "💰",
    badge: "Premium",
    features: JSON.stringify([
      "Prospecção ativa B2B",
      "Negociação avançada",
      "Follow-up enterprise",
      "Propostas comerciais",
      "Gestão de stakeholders",
    ]),
    requirements: JSON.stringify(["Produto/serviço B2B", "Processo comercial"]),
    integrations: JSON.stringify(["LinkedIn Sales Navigator", "Apollo", "CRM"]),
    useCases: JSON.stringify(["Vendas enterprise", "Alto ticket", "Corporações"]),
    targetAudience: "enterprise" as const,
    status: "active" as const,
    sortOrder: 29,
  },
  {
    name: "MMN Rede Master",
    slug: "mmn-rede-avancado",
    description: "Ferramentas avançadas para gestão de rede multinível com mini sites, calculadoras e gamificação.",
    shortDescription: "Ferramentas avançadas para gestão de rede multinível.",
    level: "advanced" as const,
    category: "mmn",
    subcategory: "rede",
    price: 11900,
    originalPrice: 14900,
    iconEmoji: "🌐",
    badge: null,
    features: JSON.stringify([
      "Mini site de reclutamento",
      "Calculadora de bônus",
      "Gamificação",
      "Ranking de afiliados",
      "Automação de onboarding",
    ]),
    requirements: JSON.stringify(["Sistema MMN", "Plano de carreira"]),
    integrations: JSON.stringify(["Plataforma MMN", "WhatsApp", "E-mail"]),
    useCases: JSON.stringify(["Gestão de rede", "Recrutamento", "Motivação de equipe"]),
    targetAudience: "advanced" as const,
    status: "active" as const,
    sortOrder: 30,
  },
];

export async function seedSkills() {
  const db = await getDb();
  if (!db) {
    console.warn("[Seed] Banco de dados não disponível");
    return;
  }

  console.log("[Seed] Iniciando seed de skills...");

  for (const skillData of SEED_SKILLS) {
    try {
      // Verificar se já existe
      const existing = await db
        .select()
        .from(skills)
        .where(eq(skills.slug, skillData.slug))
        .limit(1);

      if (existing.length === 0) {
        await db.insert(skills).values({
          ...skillData,
          createdAt: new Date(),
          updatedAt: new Date(),
        });
        console.log(`[Seed] Skill criada: ${skillData.name}`);
      } else {
        console.log(`[Seed] Skill já existe: ${skillData.name}`);
      }
    } catch (error) {
      console.error(`[Seed] Erro ao criar skill ${skillData.name}:`, error);
    }
  }

  console.log("[Seed] Seed de skills concluído!");
}

// Executar se chamado diretamente
seedSkills().catch(console.error);